### ISSUE TITLE
Implement partial threshold / flow deletion logic

### ISSUE THREAD

**Issue by zanetworker** [networkmachinery/networkmachinery-operators#1]
if a list of thresholds or flows was created, it should be possible detect the removal of an item from the list and also deleting in the monitoring backend. For example if the following was created: 
 
```yaml 
  thresholds:
    - name: "ddos"
      metric: "elephant-flow"
      value: 30
      flowName: "elephant-flow"
    - name: "ddos2"
      metric: "elephant-flow"
      value: 100
      flowName: "elephant-flow"
```

Editing it to: 

```yaml 
  thresholds:
    - name: "ddos2"
      metric: "elephant-flow"
      value: 100
      flowName: "elephant-flow"
```

should already remove the second threshold from the monitoring backend.
